/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Parser.MathFunctionsParser;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author Atabord
 */
public class Secante extends javax.swing.JFrame {
    private double _xi;
    private double _xs;
    private double _tolerance;
    private int _n;
    private final MathFunctionsParser function;
    /**
     * Creates new form Secante
     */
    public Secante() {
        this.function = new MathFunctionsParser();
        initComponents();
        onExit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JFrame();
        titleLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        initialValueLbl = new javax.swing.JLabel();
        xiInput = new javax.swing.JTextField();
        toleranceLbl = new javax.swing.JLabel();
        toleranceInput = new javax.swing.JTextField();
        functionLbl = new javax.swing.JLabel();
        functionInput = new javax.swing.JTextField();
        secondValueLbl = new javax.swing.JLabel();
        nitterLbl = new javax.swing.JLabel();
        xsInput = new javax.swing.JTextField();
        nInput = new javax.swing.JTextField();
        plotterBtn = new javax.swing.JButton();
        calculateBtn = new javax.swing.JButton();
        cleanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        secantTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        observations = new javax.swing.JTextPane();
        infoButton = new javax.swing.JButton();

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titleLbl.setBackground(new java.awt.Color(254, 254, 254));
        titleLbl.setFont(new java.awt.Font("Lato Black", 1, 35)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(1, 1, 1));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("SECANTE");
        titleLbl.setToolTipText("");

        initialValueLbl.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        initialValueLbl.setForeground(new java.awt.Color(1, 1, 1));
        initialValueLbl.setText("Intervalo inferior (x0):");

        xiInput.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        xiInput.setForeground(new java.awt.Color(1, 1, 1));
        xiInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        toleranceLbl.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        toleranceLbl.setForeground(new java.awt.Color(1, 1, 1));
        toleranceLbl.setText("Tolerancia:");

        toleranceInput.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        toleranceInput.setForeground(new java.awt.Color(1, 1, 1));

        functionLbl.setFont(new java.awt.Font("Lato Black", 1, 20)); // NOI18N
        functionLbl.setForeground(new java.awt.Color(1, 1, 1));
        functionLbl.setText("f(x) = ");

        functionInput.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        functionInput.setForeground(new java.awt.Color(1, 1, 1));

        secondValueLbl.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        secondValueLbl.setForeground(new java.awt.Color(1, 1, 1));
        secondValueLbl.setText("Intervalo superior (x1):");

        nitterLbl.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        nitterLbl.setForeground(new java.awt.Color(1, 1, 1));
        nitterLbl.setText("Máximas iteraciones (n):");

        xsInput.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        xsInput.setForeground(new java.awt.Color(1, 1, 1));

        nInput.setFont(new java.awt.Font("Lato Black", 0, 15)); // NOI18N
        nInput.setForeground(new java.awt.Color(1, 1, 1));

        plotterBtn.setBackground(new java.awt.Color(0, 149, 136));
        plotterBtn.setFont(new java.awt.Font("Lato Black", 1, 15)); // NOI18N
        plotterBtn.setForeground(new java.awt.Color(1, 1, 1));
        plotterBtn.setText("GRAFICAR");
        plotterBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        plotterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotterBtnActionPerformed(evt);
            }
        });

        calculateBtn.setBackground(new java.awt.Color(0, 149, 136));
        calculateBtn.setFont(new java.awt.Font("Lato Black", 1, 15)); // NOI18N
        calculateBtn.setForeground(new java.awt.Color(1, 1, 1));
        calculateBtn.setText("CALCULAR");
        calculateBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        cleanBtn.setBackground(new java.awt.Color(0, 149, 136));
        cleanBtn.setFont(new java.awt.Font("Lato Black", 1, 15)); // NOI18N
        cleanBtn.setForeground(new java.awt.Color(1, 1, 1));
        cleanBtn.setText("LIMPIAR");
        cleanBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(functionLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(functionInput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(toleranceLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(toleranceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(initialValueLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(xiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(secondValueLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(xsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nitterLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(cleanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(plotterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initialValueLbl)
                    .addComponent(secondValueLbl)
                    .addComponent(xsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toleranceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toleranceLbl)
                    .addComponent(nitterLbl)
                    .addComponent(nInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(functionLbl)
                    .addComponent(functionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plotterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        secantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "xm", "f(xm)", "den", "Error"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        secantTable.setColumnSelectionAllowed(true);
        secantTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(secantTable);
        secantTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        backBtn.setBackground(new java.awt.Color(26, 118, 210));
        backBtn.setFont(new java.awt.Font("Lato Black", 1, 15)); // NOI18N
        backBtn.setForeground(new java.awt.Color(1, 1, 1));
        backBtn.setText("ATRAS");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        observations.setEditable(false);
        observations.setText("OBSERVACIONES:");
        observations.setToolTipText("");
        jScrollPane3.setViewportView(observations);

        infoButton.setText("?");
        infoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        infoButton.setFocusable(false);
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infoButton)))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void onExit() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    private void plotterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotterBtnActionPerformed
        PlotterVisual fra = new PlotterVisual(functionInput.getText());
        fra.setVisible(true);
    }//GEN-LAST:event_plotterBtnActionPerformed

    private boolean validateForm () {
        String functionInputText = this.functionInput.getText();
        try {
            this._xi = Double.parseDouble(this.xiInput.getText());
            this._xs = Double.parseDouble(this.xsInput.getText());
            this._tolerance = Double.parseDouble(this.toleranceInput.getText());
            this._n = Integer.parseInt(this.nInput.getText());
            function.parserFunction(functionInputText);
        } catch (Exception e) {
            this.observations.setForeground(Color.red);
            this.observations.setText("Error: Por favor verifica que los campos no estén vacíos y tengan valores correctos");
            return false;
        }
        this.observations.setForeground(Color.black);
        this.observations.setText("OBSERVACIONES:");
        return true;
    }
    
    private void fillTable (int n, double xm, double ym, double den , double error) {
        NumberFormat numFormat = new DecimalFormat("0.##E0");
        DefaultTableModel bisectionTableModel = (DefaultTableModel) secantTable.getModel();
        Object[] row = new Object[5];
        row[0] = n;
        row[1] = xm;
        row[2] = numFormat.format(ym);
        row[3] = den;
        row[4] = numFormat.format(error);
        bisectionTableModel.addRow(row);
    }
    
    private double f(double x) {
        this.function.function.addVariable("x", x);
        Double result = function.function.getValue();
        if(Double.isNaN(result)){
            throw new ArithmeticException("Por favor verifica que el campo de la funcion este correctamente redactado y en funcion de x");
        }
        return result;
    }
    
    private void secantMethod(double x0, double x1, double tolerance, int n){
        double fx0 = f(x0);
        fillTable(0, x0, fx0, 0, 0);
        double fx1 = f(x1);
        if (fx0 == 0) {
            this.observations.setText(x0 + " es una raiz");
        }
        else if (tolerance < 0) {
            this.observations.setText("La tolerancia debe ser mayor o igual a cero");
        } else if (n <= 0) {
            this.observations.setText("Las iteraciones deben ser positivas");
        } else {
            int count = 1;
            double error = Math.abs(x1-x0);
            double den = fx1 - fx0;
            fillTable(count, x1, fx1, den, error);
            while (fx1 != 0 && error > tolerance && den != 0 && count < n){
              double x2 = x1 - fx1*(x1-x0)/den;
              error = Math.abs(x2 - x1);
              x0 = x1;
              fx0 = fx1;
              x1 = x2;
              fx1 = f(x1);
              den = fx1 - fx0;
              count++;
              fillTable(count, x1, fx1, den, error);
          }
          if (fx1 == 0) {
            this.observations.setText("Se encontró una raíz en x =" + x1 + "\n\nIteraciones necesarias: " + count);
          }
          else if (error <= tolerance) {
            this.observations.setText(x1 + " se aproxima a una raíz debido a que el error " + error + " es menor o igual a la tolerancia " + tolerance + "\n\n Y fue logrado en " + count + " iteraciones.");
          }
          else if (den == 0) {
            this.observations.setText("Hay una posible raíz multiple");
          } else {
            this.observations.setText("El algoritmo fracasó en "+ count + " iteraciones");
          }
        }
    }
    
    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        if(this.validateForm()){
            try {
                clearTable();
                secantMethod(_xi, _xs, _tolerance, _n);
            } catch (Exception e) {
                observations.setText("Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_calculateBtnActionPerformed

        private void clearTable() {
        DefaultTableModel bisectionTableModel = (DefaultTableModel) secantTable.getModel();
        bisectionTableModel.setRowCount(0);
    }
    
    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtnActionPerformed
        this.xiInput.setText("");
        this.xsInput.setText("");
        this.nInput.setText("");
        this.toleranceInput.setText("");
        this.functionInput.setText("");
        this.clearTable();
        this.observations.setText("OBSERVACIONES:");
    }//GEN-LAST:event_cleanBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        JOptionPane.showMessageDialog(dialog, "Este método necesita dos valores iniciales X0 y X1 los cuales son los extremos de un intervalo\nque contiene una raíz.\n\nPero este método no esta clasificado entre los métodos que usa intervalos.\n\nAdemas también recibe iteraciones y tolerancia.\n\nPara calcular Xn en la tercera iteracion se usa la formula:\n\n\tg(Xn) = Xn - (f(Xn)(Xn-Xn-1)/f(Xn) - f(Xn-1)\n\nQue es la variación con respecto al método de newton\ny se puede tener en cuenta como una aproximación a la derivada\n\nAdemas de que este método puede divergir y no es de orden lineal si no super-lineal. ");
    }//GEN-LAST:event_infoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JFrame dialog;
    private javax.swing.JTextField functionInput;
    private javax.swing.JLabel functionLbl;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel initialValueLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nInput;
    private javax.swing.JLabel nitterLbl;
    private javax.swing.JTextPane observations;
    private javax.swing.JButton plotterBtn;
    private javax.swing.JTable secantTable;
    private javax.swing.JLabel secondValueLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField toleranceInput;
    private javax.swing.JLabel toleranceLbl;
    private javax.swing.JTextField xiInput;
    private javax.swing.JTextField xsInput;
    // End of variables declaration//GEN-END:variables
}
