package GUI;

import java.math.BigDecimal;

/**
 *
 * @author Jose David Henao Ocampo
 */
public class SplinesCubico extends javax.swing.JFrame {

    /**
     * Creates new form SplinesLineal
     */
    private DatosInterpolacion datosInterpolacion;
    private BigDecimal[]x;
    private BigDecimal[]xn;
    private int sinderivarpotencias[] = {3,2,1,0};
    private int derivada1coeficientes[] = {3,2,1,0};
    private int derivada1potencia[] = {2,1,0,0};
    private int derivada2coeficientes[] = {6,2,0,0};
    private int derivada2potencia[] = {2,1,0,0};
    BigDecimal intervalos[][] = new BigDecimal[x.length-1][2];
    
    
    public SplinesCubico() {
        datosInterpolacion = DatosInterpolacion.getDatosInterpolacion();
        x = datosInterpolacion.getX();
        xn = datosInterpolacion.getXn();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SPLINES CUBICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void splineCubico(){
        
    }
    
    public void incializarintervalos(){
        for(int i = 0 ;i<intervalos.length;i++){
            for(int j = 0;j<intervalos[0].length;j++){
                intervalos[i][j]= x[j-i];
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
